---
title: "p8105_hw5_jt3174"
author: "Jingyi"
date: "11/6/2019"
output: github_document
---

```{r set up, include = FALSE}
# knitr will run the chunk but not include the chunk in the final document

# ensure reproductivity
set.seed(1)

# load library
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

# Problem 1

```{r load data}

# load data as copied from Jeff
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

```{r fill missing values}

# write a function that fill all missing numeric variables with the mean of non-missing values and all missing categorical variables with virginica

filling = function(column) {
  # make sure the argument is a vector, and if not, stop
  if (!is.vector(column)) {
    stop("Argument should be a vector.")
  }
  # to distinguish numeric variable 
  if (is.numeric(column)) {
    # to make sure we have all orginal data in the output
    column = column %>% 
    # to replace all missing data with the mean of what are not missing in the vector argument
    replace_na(mean(column[!is.na(column)])) 
  }
  # for all other left variables, dintinguish whether this is a categorical variable
  else if (is.character(column)) {
    # make sure we have all original data in the output
    column = column %>% 
    # to replace all missing data with virginica
    str_replace_na("virginica") 
  }
  
}

# use map to iterate over each variable of the dataframe iris_with_missing with filling function that I just wrote above and return a dataframe called iris_filled
iris_filled = map_df(iris_with_missing, filling)

```

# Problem 2

```{r read data, message = FALSE}

# vector for pathes of files
path = list.files(path = "./data/", full.names = TRUE)

# function for paths of files to be read and combined
read_and_combine = function(x) {
  data = read_csv(x)
  cbind(file_id = x, data)
}

# read data
arm_study = purrr::map_df(path, read_and_combine) %>% 
  # get rid of the same ./data/ in the beginning
  mutate(file_id = str_extract(file_id, "[conexp]{3}_[0-9]{2}")) %>% 
  # to get two columns: subject ID and arm
  separate(file_id, into = c("arm", "subject_id"), sep = "_") %>% 
  # reorder the variables
  select(subject_id, arm, everything())

arm_study

```


